window.BT=window.BT||{};
BT.annualReports=(()=>{
  const pending=new Map();
  const who=()=>BT.auth?.isAuthenticated?.()&&!BT.auth?.isGuest?.()?BT.auth.getCurrentUser()?.id||'guest':'guest';
  function years(state){const current=new Date().getFullYear();const values=[...(state.sessions||[]).map(s=>s.startedAt),...(state.lexicon||[]).map(e=>e.createdAt||e.updatedAt),...(state.traces||[]).map(t=>t.createdAt),...(state.books||[]).filter(b=>b.libraryState==='library').flatMap(b=>[b.startedAt,b.completedAt,b.addedAt]),...(state.timeline||[]).map(e=>e.date)];return [...new Set(values.filter(Boolean).map(v=>new Date(v).getFullYear()).filter(y=>y>=1900&&y<=current))].sort((a,b)=>b-a);}
  async function reportId(account,year){const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('boop-annual-v1:'+account+':'+year)));bytes[6]=(bytes[6]&15)|80;bytes[8]=(bytes[8]&63)|128;const s=[...bytes.slice(0,16)].map(b=>b.toString(16).padStart(2,'0')).join('');return `${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`;}
  async function generate(year,{replace=false}={}){const account=who(),key=account+':'+year;if(pending.has(key))return pending.get(key);const job=(async()=>{const existing=(await BT.readingCards.cached(account)).find(c=>c.month_key===String(year));if(existing&&!replace)return existing;const data=BT.monthlyReport.buildData(BT.store.getState(),String(year),false),canvas=await BT.monthlyReport.render(data);if(who()!==account)throw new Error('Le compte a changé.');return BT.readingCards.save(canvas,data,{id:replace?crypto.randomUUID():await reportId(account,year)});})();pending.set(key,job);try{return await job;}finally{pending.delete(key);}}
  function mount(host){const account=who(),available=years(BT.store.getState()),current=new Date().getFullYear();const tools=document.createElement('div'),cards=document.createElement('div'),status=document.createElement('p');tools.className='annual-report-tools card';tools.innerHTML='<h3>Un regard sur mon année</h3><p class="small muted">Les bilans des années terminées sont préparés à l’ouverture du Sentier. Ils restent privés jusqu’à leur publication.</p><form class="button-row"><label class="field">Année<select name="year"></select></label><button type="submit" class="button button--secondary">Créer un bilan</button></form>';const select=tools.querySelector('select');for(const year of available.length?available:[current]){const option=document.createElement('option');option.value=year;option.textContent=year+(year===current?' · en cours':'');select.append(option);}status.className='small muted';status.setAttribute('role','status');tools.append(status);host.append(tools,cards);BT.readingCards.mount(cards,{period:'year',layout:'list'});
    const valid=()=>host.isConnected&&who()===account;tools.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=tools.querySelector('button');button.disabled=true;status.textContent='Création du bilan…';try{await generate(Number(select.value),{replace:true});if(valid())status.textContent='Bilan enregistré dans votre Sentier.';}catch(error){if(valid())status.textContent=error.message;}finally{if(valid())button.disabled=false;}};
    (async()=>{try{for(const year of available.filter(y=>y<current)){if(!valid())return;status.textContent='Préparation du bilan '+year+'…';await generate(year);}if(valid())status.textContent='';}catch(error){if(valid())status.textContent='Le bilan pourra être créé avec le bouton ci-dessus. '+error.message;}})();
  }
  return {years,reportId,generate,mount};
})();
