/* One menu for community, club and card publications. Server policies remain authoritative. */
window.BT=window.BT||{};
BT.publications=(()=>{
  const records=new Map(),expanded=new Set(),dialogs=new Map();let scope='';
  const who=()=>BT.auth?.isAuthenticated?.()&&!BT.auth?.isGuest?.()?BT.auth.getCurrentUser()?.id:null;
  const moderator=()=>!!who()&&BT.staffAccess?.isModerator()===true;
  window.addEventListener('boop:staff-access-changed',()=>{
    document.querySelectorAll('[data-publication-menu]').forEach(menu=>{
      const item=records.get(menu.dataset.publicationMenu);if(!item||item.mine||item.canManage)return;
      const button=menu.querySelector('[data-publication-command="delete"]');
      const allowed=item.account===who()&&moderator()&&item.visibility!=='private'&&item.visibility!=='me';
      if(!allowed){button?.remove();return;}
      if(!button){const action=document.createElement('button');action.type='button';action.dataset.publicationCommand='delete';action.textContent='Supprimer';menu.querySelector('.publication-menu-panel')?.append(action);}
    });
  });
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function record(post,options={}){const current=who()||'guest';if(current!==scope){records.clear();expanded.clear();scope=current;}const value={...post,...options},table=options.table||'community_posts',id=post.remoteId||post.id,key=table+':'+id;const author=post.author_id||post.user_id||post.authorId;records.set(key,{...value,table,id,account:current,mine:author==='me'||author===(table==='reading_cards'?(who()||'guest'):who()),remote:options.remote??post.isRemote??!!(post.author_id||post.user_id&&post.synced)});return key;}
  function menuHTML(post,options={}){const key=record(post,options),item=records.get(key);return `<details class="publication-menu" data-publication-menu="${escape(key)}"><summary class="icon-button" aria-label="Actions de la publication" title="Actions de la publication">•••</summary><div class="publication-menu-panel">${item.mine?'<button type="button" data-publication-command="edit">Modifier</button>':''}<button type="button" data-publication-command="share">Partager</button>${!item.mine?'<button type="button" data-publication-command="report">Signaler</button>':''}${item.mine||(moderator()&&item.visibility!=='private'&&item.visibility!=='me')||item.canManage?'<button type="button" data-publication-command="delete">Supprimer</button>':''}</div></details>`;}
  function menu(post,options={}){const host=document.createElement('div');host.innerHTML=menuHTML(post,options);return host.firstElementChild;}
  function previewHTML(html,id){const key=String(id||'');return `<div class="publication-preview ${expanded.has(key)?'':'is-collapsed'}" data-publication-preview="${escape(key)}">${html}</div><button class="text-link publication-more" type="button" data-publication-expand="${escape(key)}" aria-expanded="${expanded.has(key)}" hidden>${expanded.has(key)?'Moins':'Plus'}</button>`;}
  function modal(title){const d=document.createElement('dialog');d.className='app-dialog publication-action-dialog';d.innerHTML=`<div class="dialog-head"><h2>${escape(title)}</h2><button type="button" class="icon-button" aria-label="Fermer">×</button></div><div class="dialog-body"></div>`;const h=d.querySelector('h2');h.id='publication-'+crypto.randomUUID();d.setAttribute('aria-labelledby',h.id);d.querySelector('button').onclick=()=>d.close();document.body.append(d);dialogs.set(d,who());d.onclose=()=>{dialogs.delete(d);d.remove();};d.showModal();return {d,body:d.querySelector('.dialog-body')};}
  function changed(item){if(item.table==='community_posts')BT.store.removeCommunityPost(item.id);window.dispatchEvent(new Event(item.remote?'boop:sharing-changed':'boop:local-post-changed'));if(item.table==='reading_cards')window.dispatchEvent(new Event('boop:reading-cards-changed'));if(item.table==='reading_club_posts')document.dispatchEvent(new CustomEvent('boop:club-publication-changed',{detail:item.clubId||item.club_id}));}
  async function ready(expected){await BT.auth.ready();if(!expected||who()!==expected)throw new Error('Votre compte a changé. Rouvrez la publication.');return BT.auth.getClient();}
  function result(r){if(r.error)throw new Error(r.error.code==='23505'?'Ce signalement a déjà été enregistré.':r.error.code==='42501'?'Cette action n’est pas autorisée pour ce compte.':'L’action n’a pas été enregistrée. Vérifiez la connexion et réessayez.');return r.data;}
  function plain(item){const kind=item.readingKind||item.reading_kind,content=item.readingContent||item.reading_content||'';return [item.bookTitle||item.book_title||item.title,kind==='citation'?Object.values(BT.sharing.citation(content)).join('\n'):kind==='thought'?BT.sharing.thought(content).text:content,item.text||item.body||item.caption].filter(Boolean).join('\n\n');}
  function share(item){if(item.table==='reading_cards')return shareCard(item);const data={title:item.bookTitle||item.book_title||item.title||'Une lecture sur BOO-P',text:plain(item)};if(item.remote&&item.visibility==='public'&&item.table==='community_posts'){
      const url=new URL('app.html#community?publication='+encodeURIComponent(item.id),BT.native?.isNative?BT.native.publicAppUrl:location.href);
      if(!BT.native?.isNative||url.protocol==='https:'&&!url.username&&!url.password)data.url=url.href;
    }
    if(navigator.share){navigator.share(data).catch(e=>{if(e.name!=='AbortError')copyDialog(data);});}else copyDialog(data);
  }
  function shareCard(item){
    if(!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(item.image_data||''))return;
    const bytes=Uint8Array.from(atob(item.image_data.split(',')[1]),c=>c.charCodeAt(0)),file=new File([bytes],'boo-p-'+item.month_key+'.jpg',{type:'image/jpeg'}),data={title:item.title,text:item.caption||'',files:[file]};
    const fallback=()=>{const {body}=modal('Partager la carte'),link=document.createElement('a');link.className='button button--primary';link.textContent='Télécharger l’image';link.href=item.image_data;link.download=file.name;body.append(Object.assign(document.createElement('p'),{textContent:'Enregistrez l’image puis choisissez-la dans l’application de votre choix.'}),link);};
    if(navigator.share&&navigator.canShare?.({files:[file]}))navigator.share(data).catch(e=>{if(e.name!=='AbortError')fallback();});else fallback();
  }
  function copyDialog(data){const {body}=modal('Partager la publication');const text=[data.text,data.url].filter(Boolean).join('\n\n');body.innerHTML=`<label class="field">Texte à partager<textarea rows="8" readonly>${escape(text)}</textarea></label><button type="button" class="button button--primary">Copier</button><p role="status"></p>`;body.querySelector('button').onclick=async()=>{try{await navigator.clipboard.writeText(text);body.querySelector('[role=status]').textContent='Texte copié. Collez-le dans l’application de votre choix.';}catch{body.querySelector('textarea').select();body.querySelector('[role=status]').textContent='Sélectionnez puis copiez le texte.';}};}
  function report(item){const {d,body}=modal('Signaler la publication'),account=who();if(!account||!item.remote){body.textContent='Connectez-vous pour signaler une publication en ligne.';return;}
    body.innerHTML='<form class="form-grid"><label class="field">Motif<select name="reason"><option>Harcèlement ou propos haineux</option><option>Contenu inapproprié</option><option>Spam ou publicité</option><option>Atteinte à la vie privée</option><option>Autre motif</option></select></label><label class="field">Précisions · facultatives<textarea name="detail" maxlength="2000" rows="4"></textarea></label><button type="submit" class="button button--primary">Envoyer le signalement</button><p role="status"></p></form>';
    body.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button');button.disabled=true;try{const client=await ready(account),field=({community_posts:'post_id',reading_club_posts:'club_post_id',reading_cards:'card_id'})[item.table];result(await client.from('publication_reports').insert({reporter_id:account,[field]:item.id,reason:form.elements.reason.value,details:form.elements.detail.value.trim()}));if(who()!==account||!d.isConnected)return;form.replaceChildren(Object.assign(document.createElement('p'),{textContent:'Votre signalement est enregistré. Merci de nous aider à préserver cet espace de lecture.'}));}catch(error){if(d.isConnected){form.querySelector('[role=status]').textContent=error.message;button.disabled=false;}}};
  }
  function remove(item){const {d,body}=modal('Supprimer la publication'),account=who();body.innerHTML='<p>Supprimer cette publication et ses échanges ? Votre contenu personnel reste dans votre Carnet.</p><div class="button-row"><button type="button" class="button button--secondary" data-cancel>Annuler</button><button type="button" class="button button--primary" data-confirm>Supprimer</button></div><p role="status"></p>';if(item.table==='reading_cards')body.querySelector('p').textContent='Supprimer cette carte et sa publication ? L’image enregistrée sera retirée de votre Sentier.';body.querySelector('[data-cancel]').onclick=()=>d.close();body.querySelector('[data-confirm]').onclick=async e=>{e.target.disabled=true;try{
      if(item.table==='reading_cards')await BT.readingCards.remove(item,account);
      else if(item.remote){const client=await ready(account);let query=client.from(item.table).delete().eq('id',item.id);if(item.mine)query=query.eq('author_id',account);const rows=result(await query.select('id'));if(!rows?.length)throw new Error('Cette publication n’est plus accessible.');}
      else if(item.table==='reading_club_posts'){if(!BT.store.removeGroupPost(item.clubId,item.id))throw new Error('Cette publication ne peut pas être supprimée.');}
      else if(item.mine&&item.table==='community_posts')BT.store.removeCommunityPost(item.id);
      else throw new Error('Cette publication ne peut pas être supprimée.');
      if(who()!==account||!d.isConnected)return;changed(item);d.close();
    }catch(error){if(d.isConnected){body.querySelector('[role=status]').textContent=error.message;e.target.disabled=false;}}};}
  function edit(item){if(!item.mine)return;if(item.table==='reading_cards')return BT.readingCards.editPublication(item);if(item.table==='community_posts')return item.author_id?BT.sharing.editRemotePost(item):BT.sharing.editPost({...item,authorId:'me'});
    const {d,body}=modal('Modifier ma publication'),account=who();body.innerHTML=`<form class="form-grid"><label class="field">Texte<textarea name="text" maxlength="1200" required rows="8">${escape(item.text||item.body)}</textarea></label><button type="submit" class="button button--primary">Enregistrer</button><p role="status"></p></form>`;body.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.target,save=form.querySelector('button');save.disabled=true;try{if(!item.remote){if(!BT.store.updateGroupPost(item.clubId,item.id,form.elements.text.value))throw new Error('Cette publication ne peut pas être modifiée.');changed(item);d.close();return;}const client=await ready(account),rows=result(await client.from('reading_club_posts').update({body:form.elements.text.value.trim()}).eq('id',item.id).eq('author_id',account).select('id'));if(!rows?.length)throw new Error('Cette publication n’est plus accessible.');if(who()!==account||!d.isConnected)return;changed(item);d.close();}catch(error){if(d.isConnected){form.querySelector('[role=status]').textContent=error.message;save.disabled=false;}}};
  }
  document.addEventListener('click',e=>{const b=e.target.closest('[data-publication-command]');if(b){const details=b.closest('[data-publication-menu]'),item=records.get(details.dataset.publicationMenu);details.open=false;if(!item||item.account!==(who()||'guest'))return;({edit,share,report,delete:remove})[b.dataset.publicationCommand]?.(item);return;}const more=e.target.closest('[data-publication-expand]');if(more){const key=more.dataset.publicationExpand,on=!expanded.has(key);if(on)expanded.add(key);else expanded.delete(key);more.previousElementSibling.classList.toggle('is-collapsed',!on);more.textContent=on?'Moins':'Plus';more.setAttribute('aria-expanded',String(on));return;}document.querySelectorAll('.publication-menu[open],.reader-profile-menu[open]').forEach(d=>{if(!d.contains(e.target))d.open=false;});});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){const menu=e.target.closest('.publication-menu[open],.reader-profile-menu[open]');if(menu){e.preventDefault();menu.open=false;menu.querySelector('summary').focus();}}});
  document.addEventListener('DOMContentLoaded',()=>{const observed=new Set(),observer=new ResizeObserver(entries=>{for(const {target} of entries){const b=target.nextElementSibling;if(b?.matches('[data-publication-expand]')){b.hidden=target.classList.contains('is-collapsed')&&target.scrollHeight<=target.clientHeight+1;target.id||='preview-'+crypto.randomUUID();b.setAttribute('aria-controls',target.id);}}});const scan=()=>{for(const n of observed)if(!n.isConnected){observer.unobserve(n);observed.delete(n);}document.querySelectorAll('[data-publication-preview]').forEach(n=>{if(!observed.has(n)){observed.add(n);observer.observe(n);}});};new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});scan();BT.store.subscribe(()=>{for(const [d,account] of dialogs)if(who()!==account)d.close();});});
  return {menuHTML,menu,previewHTML,report,share};
})();
