import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../js/store.js',import.meta.url),'utf8');
function setup(){const memory=new Map();let blocked=false;const storage={getItem:k=>memory.get(k) || null,setItem:(k,v)=>{if(blocked)throw new Error('QuotaExceededError');memory.set(k,String(v));},removeItem:k=>memory.delete(k)};const load=()=>{const BT={};vm.runInNewContext(source,{BT,window:{BT,addEventListener(){}},localStorage:storage,navigator:{onLine:false},console,TextEncoder});return BT.store;};return {load,block:v=>blocked=v};}
test('carnet libre: texte et sections survivent au rechargement sans conversation IA',()=>{const s=setup(),store=s.load();store.useUser('reader');const book=store.addBook({title:'Mémoires d’Hadrien'});const reflection={notebook:'Je peux douter et avancer.',sections:{retained:'La lucidité',questions:'Comment rester ouvert ?'},messages:[]};assert.equal(store.saveBookReflection(book.id,reflection),true);const reloaded=s.load();reloaded.useUser('reader');assert.deepEqual(JSON.parse(JSON.stringify(reloaded.getBookById(book.id).reflection)),reflection);reloaded.useUser('another-reader');assert.equal(reloaded.getBookById(book.id),null);});
test('carnet: un échec de stockage ne remplace pas le dernier texte enregistré',()=>{const s=setup(),store=s.load(),id=store.getBooks()[0].id;assert.equal(store.saveBookReflection(id,{notebook:'Version conservée'}),true);s.block(true);assert.equal(store.saveBookReflection(id,{notebook:'Nouvelle version'}),false);assert.equal(store.getBookById(id).reflection.notebook,'Version conservée');s.block(false);assert.equal(s.load().getBookById(id).reflection.notebook,'Version conservée');});
test('carnet: une entrée trop volumineuse reste refusée avant écriture',()=>{const s=setup(),store=s.load(),id=store.getBooks()[0].id;assert.equal(store.saveBookReflection(id,{notebook:'é'.repeat(150000)}),false);assert.equal(store.getBookById(id).reflection,null);});
