import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {webcrypto} from 'node:crypto';
const read=f=>readFile(new URL('../'+f,import.meta.url),'utf8');
async function setup(memory=new Map()){
 const context={console,Date,Math,JSON,Set,Map,URL,TextEncoder,Uint8Array,crypto:webcrypto,navigator:{onLine:true},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k)},window:{BT:{},addEventListener(){},BOOP_SUPABASE_CONFIG:{url:'https://shnyjvinzjvgourpscvh.supabase.co'}},setTimeout,clearTimeout};context.BT=context.window.BT;context.BT.auth={getCurrentUser:()=>({id:'reader'})};vm.createContext(context);for(const f of ['thought-editor','store','reading-sharing','reading-experience','monthly-report','annual-reports'])vm.runInContext(await read('js/'+f+'.js'),context);context.BT.store.useUser('reader');return {...context.BT,memory};
}
test('tirage : tous les souvenirs deviennent accessibles, sans doublon dans une série',async()=>{const x=await setup(),items=Array.from({length:27},(_,id)=>({id,word:'mot '+id})),seen=new Set();for(let n=0;n<3;n++){const deck=x.readingExperience.deck('test',items,{refresh:true});assert.equal(deck.length,10);assert.equal(new Set(deck.map(i=>i.id)).size,10);deck.forEach(i=>seen.add(i.id));}assert.equal(seen.size,27);const current=x.readingExperience.deck('test',items);const changed=items.map(i=>({...i,word:'nouveau '+i.id}));assert.ok(x.readingExperience.deck('test',changed).every(i=>i.word.startsWith('nouveau')));assert.deepEqual(current.map(i=>i.id),x.readingExperience.deck('test',changed).map(i=>i.id));assert.equal(x.readingExperience.deck('empty',[]).length,0);assert.equal(x.readingExperience.deck('small',[{id:1}]).length,1);assert.equal(x.readingExperience.deck('duplicate',[{id:1},{id:1}]).length,1);});
test('fiche : réponses privées conservées après redémarrage et synchronisation',async()=>{const a=await setup(),book=a.store.addBook({title:'Mon livre',authors:['A']});a.readingExperience.saveSheet(book.id,{type:'fiction',answers:{summary:'Un voyage.',impact:'Une idée à suivre.'}});const b=await setup(a.memory),sheet=b.store.getBookById(book.id).readingSheet;assert.equal(sheet.answers.summary,'Un voyage.');assert.match(b.readingExperience.sheetText(sheet),/Une idée à suivre/);assert.equal(b.readingExperience.sheetText(null),'');const c=await setup();c.store.replaceSyncedData(b.store.getSyncedData());assert.equal(c.store.getBookById(book.id).readingSheet.answers.impact,'Une idée à suivre.');assert.equal(b.store.getCommunity().posts.filter(p=>p.text?.includes('Un voyage.')).length,0);});
test('pensée : sujet modifiable conservé et échappé dans la copie publiée',async()=>{const a=await setup(),b=a.store.addBook({title:'Livre'});const t=a.store.saveTrace({bookId:b.id,subject:'<script>Mon sujet</script>',text:'Mon texte',formatting:{version:1,runs:[{text:'Mon texte',bold:true}]}});a.store.saveTrace({id:t.id,text:'Mon texte'});const saved=a.store.getTraces().find(x=>x.id===t.id);assert.equal(saved.subject,'<script>Mon sujet</script>');const pub=a.sharing.source('thought',t.id);assert.equal(a.sharing.thought(pub.content).subject,saved.subject);const html=a.sharing.publicationHTML('thought',pub.content);assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));});
test('couvertures : raster personnel accepté, SVG, hôte trompeur et URL arbitraire rejetés',async()=>{const {readingExperience:x}=await setup();for(const url of ['data:image/jpeg;base64,AAAA','data:image/png;base64,AAAA','https://covers.openlibrary.org/b/id/1.jpg','https://shnyjvinzjvgourpscvh.supabase.co/functions/v1/cover-image-proxy?url=x'])assert.equal(x.safeCover(url),url);for(const url of ['data:image/svg+xml;base64,AAAA','javascript:alert(1)','https://books.google.com.evil.test/a.jpg','https://evil.test/a.jpg','https://shnyjvinzjvgourpscvh.supabase.co/storage/v1/object/public/profile-avatars/private.jpg','data:image/jpeg;base64,'+'A'.repeat(2200000)])assert.equal(x.safeCover(url),'');});
test('bilan annuel : douze mois, limites de date, statut historique et notes exclues',async()=>{const {monthlyReport:r}=await setup(),state={profile:{name:'Lecteur'},books:[{id:'b',title:'Lecture au long cours',authors:[],status:'lu',libraryState:'library',startedAt:'2025-01-05',completedAt:'2026-02-02'}],sessions:[{bookId:'b',startedAt:'2025-01-15',durationSeconds:600},{bookId:'b',startedAt:'2025-12-15',durationSeconds:1200},{bookId:'b',startedAt:'2026-01-15',durationSeconds:6000}],lexicon:[{kind:'word',word:'Un mot',createdAt:'2025-06-05'}],traces:[{text:'SECRET',createdAt:'2025-08-01'}]};const data=r.buildData(state,'2025');assert.equal(data.period,'year');assert.equal(data.sessions,2);assert.equal(data.minutes,30);assert.equal(data.words,1);assert.equal(data.books[0].status,'en-cours');assert.equal(data.notes.length,0);assert.ok(!JSON.stringify(data).includes('SECRET'));assert.match(data.summary,/cette année/);assert.equal(r.buildData(state,'2025-01').sessions,1);});
test('bilan annuel : identité stable par année et compte, sans création en double',async()=>{const {annualReports:r}=await setup();const a=await r.reportId('alice',2025);assert.equal(a,await r.reportId('alice',2025));assert.notEqual(a,await r.reportId('bob',2025));assert.notEqual(a,await r.reportId('alice',2024));assert.match(a,/^[a-f0-9-]{36}$/);});
